"""Figure specifications — Chapters 15–20 (46 figures)."""

SPECS_C = {
    # ---------------- Chapter 15 ----------------
    "15.1": dict(t="cycle", cap="Post-market surveillance lifecycle",
        steps=["Device on market", "Collect feedback & complaints", "Vigilance reporting", "Trend & signal analysis",
               "Risk file update", "CAPA / field action", "PMS report (PMSR/PSUR)", "Design improvement"]),
    "15.2": dict(t="vflow", cap="Complaint handling process (ISO 13485 §8.2.2)",
        steps=[("Receive & log complaint", "Unique ID, device, lot, event description"),
               ("Initial assessment", "Is it a complaint? Reportable event screening"),
               ("? Meets vigilance reporting criteria?", "Death/serious injury or could recur"),
               ("Report to authority within timeline", "CDSCO / FDA MDR / EU vigilance"),
               ("Investigate root cause", "Device analysis, DHR review, trending"),
               ("Close with CAPA linkage", "Response to complainant, records complete")],
        edge_labels={2: "YES"}),
    "15.3": dict(t="matrix", cap="Global vigilance reporting timelines",
        headers=["Event", "India (MvPI)", "USA (FDA)", "EU (MDR)"],
        rows=[["Death / serious deterioration", "15 days", "30 days (5 urgent)", "15 days (10 if death)"],
              ["Public-health threat", "48 hours", "5 work days", "2 days"],
              ["Other reportable malfunction", "30 days", "30 days", "15 days"],
              ["Field safety corrective action", "Immediately + FSN", "Report of Correction/Removal", "FSCA + FSN before action"]], rh=40),
    "15.4": dict(t="vflow", cap="Recall decision and execution flow",
        steps=[("Signal identified", "Complaint trend, test failure, vigilance case"),
               ("Health hazard evaluation", "Severity, probability, exposed population"),
               ("? Field action required?", "Risk assessment decision with QA/RA/Medical"),
               ("Classify & notify authority", "Recall class I/II/III; FSN drafted"),
               ("Execute recall", "Trace via UDI/distribution records, retrieve/correct product"),
               ("Effectiveness checks & closure", "Reconciliation, final report, CAPA")],
        edge_labels={2: "YES"}),

    # ---------------- Chapter 16 ----------------
    "16.1": dict(t="hub", cap="Functions of medical device packaging",
        center="Packaging functions",
        spokes=[("Sterile barrier", "Maintains sterility to point of use"), ("Physical protection", "Impact, vibration, compression"),
                ("Environmental barrier", "Moisture, oxygen, light"), ("Information carrier", "Label, IFU, UDI"),
                ("Aseptic presentation", "Peel-open at the sterile field"), ("Logistics efficiency", "Handling, storage, transport")]),
    "16.2": dict(t="layers", cap="Packaging hierarchy",
        bands=[("Primary package — sterile barrier system", "Pouch/tray in direct contact; maintains sterility"),
               ("Secondary package", "Carton protecting the SBS; carries most labelling"),
               ("Shelf / dispenser pack", "Groups multiple units for clinical storage"),
               ("Transport (tertiary) packaging", "Shipper cases, pallets — ISTA/ASTM D4169 tested")]),
    "16.3": dict(t="matrix", cap="Packaging material selection",
        headers=["Material", "Strengths", "Watch-outs", "Typical use"],
        rows=[["Tyvek (HDPE)", "Sterilant-permeable, strong, clean peel", "Cost", "EO/steam pouch lids"],
              ["Medical paper", "Economical, breathable", "Fibre tear, moisture", "Steam pouches"],
              ["PET/PE films", "Clarity, seal strength", "Not gas-permeable", "Pouch base webs"],
              ["Rigid PETG trays", "Product retention, presentation", "Design cost", "Implant/kit trays"],
              ["Foil laminates", "Total barrier (O₂/moisture)", "Opaque, no EO", "Diagnostics, liquids"]], rh=38),
    "16.4": dict(t="zones", cap="Components of a sterile barrier system",
        rooms=[("Base web / tray", "Formed cavity holds device", "PETG/film"),
               ("Device + retainers", "Movement restricted", "Product"),
               ("Porous lid", "Sterilant in, microbes out", "Tyvek/paper"),
               ("Heat seal", "Continuous, peelable", "Validated"),
               ("Labelling", "UDI, symbols, expiry", "ISO 15223-1")],
        legend="The seal is the critical zone — validated for width, strength and integrity."),
    "16.5": dict(t="vflow", cap="Peel (seal-strength) testing per ASTM F88",
        steps=[("Cut standard specimen", "25 mm strip across the seal"),
               ("Mount tails in tensile grips", "Unsupported / supported technique defined"),
               ("Peel at constant speed", "200–300 mm/min typical"),
               ("Record force curve", "Average and maximum peel force"),
               ("Compare with specification", "Typical 1–4 N/15 mm clean peel, no delamination")]),
    "16.6": dict(t="flow", cap="Packaging validation workflow (ISO 11607)",
        steps=[("Material qualification", "Barrier, compatibility"), ("Process validation", "Sealer IQ/OQ/PQ"),
               ("Integrity testing", "Dye penetration, bubble leak"), ("Strength testing", "Peel, burst tests"),
               ("Transport simulation", "ASTM D4169 / ISTA"), ("Aging studies", "Accelerated + real-time"),
               ("Final report", "Shelf-life claim justified")], cols=4),
    "16.7": dict(t="profile", cap="Shelf-life determination strategy",
        x="Study duration →", y="Confidence in claim",
        phases=[("Accelerated aging starts (e.g., 55°C)", 40, 2.5),
                ("Accelerated data supports interim claim", 70, 2.5),
                ("Real-time aging continues in parallel", 80, 4),
                ("Real-time data confirms final claim", 95, 3)]),
    "16.8": dict(t="labelcard", cap="Anatomy of a compliant device label",
        title="ORTHOFIX BONE SCREW Ø4.5 × 40 mm — STERILE R",
        fields=[("REF", "BS-4540-T"), ("LOT", "LOT8817"),
                ("Sterilized by irradiation", "Do not use if package damaged"),
                ("Use-by", "2030-06"), ("Single use only", "Non-pyrogenic"),
                ("Manufacturer / EC REP", "OrthoFix Implants Ltd. / EU-Rep GmbH")]),
    "16.9": dict(t="layers", cap="Structure of a UDI",
        bands=[("UDI = DI + PI", "One barcode carries both static and dynamic parts"),
               ("DI — device identifier (static)", "Identifies manufacturer + device model; key to the UDI database"),
               ("PI — production identifiers (dynamic)", "Lot/batch, serial number, manufacture & expiry dates"),
               ("Carrier formats", "GS1-128, DataMatrix, HIBC — human-readable + machine-readable")]),
    "16.10": dict(t="timeline", cap="UDI implementation phased by device risk",
        events=[("Phase 1", "Class III / Class D — highest risk first"), ("Phase 2", "Implantable & life-sustaining"),
                ("Phase 3", "Class II / C devices"), ("Phase 4", "Class I / B devices"),
                ("Phase 5", "Direct marking for reusables"), ("Ongoing", "Database maintenance (GUDID/EUDAMED)")]),
    "16.11": dict(t="matrix", cap="Common device label symbols (ISO 15223-1)",
        headers=["Symbol meaning", "Tells the user", "Where seen"],
        rows=[["Sterile EO / R / steam", "Sterilization method used", "Sterile device labels"],
              ["Do not re-use (2 crossed)", "Single-use device", "Disposables"],
              ["Use-by (hourglass)", "Expiry date follows", "All sterile products"],
              ["LOT / REF / SN", "Batch, catalogue, serial", "All device labels"],
              ["Manufacturer / date", "Legal maker & production date", "All device labels"],
              ["Consult IFU (book)", "Read instructions before use", "Equipment & implants"]], rh=34),
    "16.12": dict(t="timeline", cap="Corrective action implementation after a labeling nonconformity",
        events=[("Day 0", "Mislabel detected; quarantine stock"), ("Day 1–3", "Health-hazard evaluation"),
                ("Week 1", "Authority notified; FSN issued if in field"), ("Weeks 2–6", "Relabel / rework under deviation control"),
                ("Week 8", "Effectiveness check"), ("Close", "CAPA closure with evidence")]),

    # ---------------- Chapter 17 ----------------
    "17.1": dict(t="hub", cap="Medical device supply chain ecosystem",
        center="Supply chain",
        spokes=[("Global manufacturers", "Export markets"), ("Importers / agents", "Licence holders (MD-15)"),
                ("Customs & regulators", "Clearance, CDSCO NOC"), ("Distributors & 3PL", "Warehousing, cold chain"),
                ("Hospitals & retail", "Point of care"), ("Reverse logistics", "Returns, recalls, disposal")]),
    "17.2": dict(t="vflow", cap="India import licence workflow (MD-14 → MD-15)",
        steps=[("Appoint authorised Indian agent", "Holds wholesale licence (Form 20B/21B or MD-42)"),
               ("Compile dossier", "DMF, PMF, free-sale certificate, ISO 13485, QMS evidence"),
               ("Apply Form MD-14 on SUGAM", "Fees per device class"),
               ("? CDSCO queries raised?", "Clarifications, additional documents"),
               ("Import licence MD-15 granted", "Port registration; consignment-wise clearance")],
        edge_labels={3: "Resolve"}),
    "17.3": dict(t="flow", cap="End-to-end supply chain workflow",
        steps=[("Factory release", "Batch documents"), ("Export packing", "Transport-validated"),
               ("Freight & customs", "Docs: invoice, MD-15, COO"), ("Bonded / QC hold", "Import verification"),
               ("Central warehouse", "GDP-compliant storage"), ("Regional distribution", "Order fulfilment"),
               ("Hospital delivery", "Proof of delivery"), ("Traceability records", "UDI-linked, recall-ready")], cols=4),
    "17.4": dict(t="zones", cap="GDP warehouse layout and zoning",
        rooms=[("Receiving bay", "Inspection, de-boxing", "Ambient"),
               ("Quarantine", "Awaiting QC release", "Segregated"),
               ("Released stock", "FEFO picking", "15–25°C"),
               ("Cold room", "2–8°C products", "Monitored"),
               ("Rejected / recall cage", "Locked, segregated", "Controlled"),
               ("Dispatch bay", "Order staging", "Ambient")],
        legend="Physical segregation of quarantine, released and rejected stock prevents mix-ups."),
    "17.5": dict(t="flow", cap="Cold chain logistics flow (2–8°C)",
        steps=[("Conditioned packout", "Qualified shippers, gel packs"), ("Data logger inside", "Continuous T-recording"),
               ("Refrigerated transport", "Validated lanes"), ("Airport / customs", "Priority handling"),
               ("Receiving check", "Logger review, excursion alarm"), ("Cold storage", "2–8°C, mapped"),
               ("Last-mile delivery", "Insulated carriers"), ("Excursion handling", "Quarantine & QA disposition")], cols=4),

    # ---------------- Chapter 18 ----------------
    "18.1": dict(t="hub", cap="Emerging-technology innovation ecosystem",
        center="Next-gen medical devices",
        spokes=[("3D printing", "Patient-specific parts"), ("Robotics", "Surgical precision"),
                ("Nanotechnology", "Targeted therapy"), ("Wearables & IoMT", "Continuous monitoring"),
                ("XR (AR/VR)", "Training & navigation"), ("AI & smart implants", "Adaptive therapy")]),
    "18.2": dict(t="flow", cap="3D-printing workflow for medical devices",
        steps=[("Patient imaging", "CT/MRI data"), ("Segmentation & CAD", "Anatomy to model"),
               ("Print preparation", "Supports, orientation"), ("Additive build", "SLS/SLA/EBM"),
               ("Post-processing", "Cleaning, heat treat, polish"), ("Sterilize & verify", "Dimensional + biocompat checks")], cols=3),
    "18.3": dict(t="flow", cap="Bioprinting process overview",
        steps=[("Cell sourcing", "Patient or donor cells"), ("Bio-ink formulation", "Cells + hydrogel matrix"),
               ("Layered printing", "Extrusion/inkjet/laser"), ("Crosslinking", "Structure stabilised"),
               ("Bioreactor maturation", "Tissue develops function"), ("Testing & application", "Research → grafts")], cols=3),
    "18.4": dict(t="layers", cap="Robotic surgery system architecture",
        bands=[("Surgeon console", "3D vision, hand controllers, ergonomic control"),
               ("Control & processing unit", "Motion scaling, tremor filtration, safety interlocks"),
               ("Patient-side cart", "Robotic arms holding instruments and endoscope"),
               ("EndoWrist-class instruments", "7-DOF articulation beyond the human wrist"),
               ("Imaging & integration", "Endoscopy, fluorescence, OR data links")]),
    "18.5": dict(t="hub", cap="Nanotechnology applications in medicine",
        center="Nanomedicine",
        spokes=[("Drug delivery", "Liposomes, nanoparticles"), ("Imaging contrast", "Quantum dots, nano-MRI agents"),
                ("Antimicrobial surfaces", "Silver nanoparticle coatings"), ("Biosensors", "Single-molecule detection"),
                ("Implant surfaces", "Nano-textured osseointegration"), ("Theranostics", "Diagnose + treat together")]),
    "18.6": dict(t="cycle", cap="Wearable device data ecosystem",
        steps=["Sensors on body", "Signal acquisition", "On-device processing", "Smartphone gateway",
               "Cloud analytics", "Clinician dashboard", "Feedback to user"]),
    "18.7": dict(t="layers", cap="Internet of Medical Things (IoMT) network architecture",
        bands=[("Perception layer", "Wearables, implants, smart equipment sensors"),
               ("Connectivity layer", "BLE, Wi-Fi, 5G, LPWAN gateways"),
               ("Edge processing", "Local filtering, alarm logic, privacy controls"),
               ("Cloud platform", "Storage, analytics, ML, interoperability APIs"),
               ("Application layer", "Clinical dashboards, EHR integration, patient apps")]),
    "18.8": dict(t="columns", cap="Extended reality across healthcare",
        cols=[("VR — virtual reality", ["Immersive surgical simulation", "Pain distraction therapy", "Phobia / rehab programmes"]),
              ("AR — augmented reality", ["Overlay of anatomy on patient", "Vein visualisation", "Surgical navigation guidance"]),
              ("MR — mixed reality", ["Holographic organ models", "Remote expert assistance", "Interactive OR planning"])]),
    "18.9": dict(t="layers", cap="Smart implant architecture",
        bands=[("Sensing elements", "Pressure, strain, temperature, biochemical markers"),
               ("Microcontroller & firmware", "Signal conditioning, safety algorithms (IEC 62304)"),
               ("Therapy delivery", "Stimulation electrodes, drug micro-pumps, actuators"),
               ("Power management", "Batteries, wireless / kinetic energy harvesting"),
               ("Telemetry & security", "Encrypted wireless link to programmer / cloud")]),
    "18.10": dict(t="flow", cap="Tissue engineering paradigm",
        steps=[("Scaffold design", "Biodegradable matrix"), ("Cell seeding", "Autologous / stem cells"),
               ("Growth factors", "Signals guide development"), ("Bioreactor culture", "Mechanical + chemical cues"),
               ("Implantation", "Construct placed in body"), ("Remodelling", "Scaffold resorbs, tissue matures")], cols=3),
    "18.11": dict(t="layers", cap="Architecture of an AI-powered medical device",
        bands=[("Data acquisition", "Sensors, imaging, physiological signals"),
               ("Pre-processing", "Noise filtering, normalisation, feature extraction"),
               ("AI inference engine", "Validated, version-locked model (PCCP for updates)"),
               ("Clinical decision output", "Alerts, classifications, dosing suggestions with confidence"),
               ("Human oversight & logging", "Clinician confirmation, audit trail, monitoring")]),
    "18.12": dict(t="hub", cap="Cybersecurity controls for connected devices",
        center="Device cybersecurity",
        spokes=[("Secure boot & firmware", "Signed updates only"), ("Encryption", "Data at rest & in transit"),
                ("Access control", "Authentication, least privilege"), ("SBOM", "Software bill of materials"),
                ("Vulnerability management", "Coordinated disclosure, patches"), ("Network segmentation", "Hospital VLAN isolation")]),

    # ---------------- Chapter 19 ----------------
    "19.1": dict(t="layers", cap="Healthcare data ecosystem architecture",
        bands=[("Data sources", "Devices, EHR/EMR, LIS/RIS-PACS, pharmacy, claims, wearables"),
               ("Integration layer", "HL7 v2, FHIR APIs, DICOM, IEEE 11073 gateways"),
               ("Data platform", "Clinical data repository, lakehouse, terminology services"),
               ("Analytics & AI", "Dashboards, predictive models, population health"),
               ("Consumption", "Clinician apps, patient portals, research, regulators")]),
    "19.2": dict(t="hub", cap="Ayushman Bharat Digital Mission (ABDM) building blocks",
        center="ABDM",
        spokes=[("ABHA health ID", "Unique patient identifier"), ("Health facility registry", "Verified providers directory"),
                ("Healthcare professional registry", "Verified practitioners"), ("Health information exchange", "Consent-based data flow"),
                ("Unified health interface", "Interoperable app layer"), ("Consent manager", "Patient-controlled sharing")]),
    "19.3": dict(t="layers", cap="FHIR-based interoperability stack",
        bands=[("FHIR resources", "Patient, Observation, Device, DiagnosticReport…"),
               ("RESTful API", "Standard HTTP verbs, JSON/XML payloads"),
               ("Terminology binding", "SNOMED CT, LOINC, ICD-11 codes"),
               ("Security layer", "OAuth 2.0 / SMART-on-FHIR authorisation"),
               ("Applications", "EHR plug-ins, device data ingestion, patient apps")]),
    "19.4": dict(t="flow", cap="IEEE 11073 medical device integration",
        steps=[("Bedside device", "Ventilator, monitor, pump"), ("11073 agent", "Standardised nomenclature"),
               ("Gateway / manager", "Protocol translation"), ("HL7/FHIR message", "Observation created"),
               ("EHR flowsheet", "Auto-charted vitals"), ("Alarms & analytics", "Downstream use")], cols=3),
    "19.5": dict(t="flow", cap="AI/ML analytics pipeline for healthcare data",
        steps=[("Data ingestion", "Batch + streaming"), ("Cleaning & harmonisation", "Deduplicate, code-map"),
               ("Feature engineering", "Clinical variables"), ("Model training", "Validated cohorts"),
               ("Evaluation", "Accuracy, fairness, drift"), ("Deployment", "APIs into workflow"),
               ("Monitoring", "Performance in production"), ("Retraining loop", "Governed updates")], cols=4),
    "19.6": dict(t="cycle", cap="IoMT data ecosystem loop",
        steps=["Connected devices", "Secure gateways", "Cloud ingestion", "Real-time analytics",
               "Clinical alerts", "Care intervention", "Outcome data back"]),
    "19.7": dict(t="layers", cap="Healthcare cloud architecture",
        bands=[("IaaS foundation", "Compute, storage, networking in certified regions"),
               ("Platform services", "Managed databases, FHIR services, ML platforms"),
               ("Security & compliance", "Encryption, IAM, audit, DPDP/HIPAA controls"),
               ("Health applications", "EHR hosting, telehealth, device data platforms"),
               ("Resilience", "Backup, disaster recovery, multi-zone availability")]),
    "19.8": dict(t="hub", cap="Health information exchange participants",
        center="HIE",
        spokes=[("Hospitals & clinics", "Encounter & discharge data"), ("Diagnostic labs", "Results reporting"),
                ("Imaging centres", "Reports & DICOM links"), ("Pharmacies", "Dispensing records"),
                ("Public health", "Registries, surveillance"), ("Patients", "Consent-managed access")]),

    # ---------------- Chapter 20 ----------------
    "20.1": dict(t="hub", cap="Medical device industry career ecosystem",
        center="MedTech careers",
        spokes=[("R&D / design", "Engineers, human factors"), ("Manufacturing", "Production, process, technicians"),
                ("Quality (QA/QC)", "Systems, testing, compliance"), ("Regulatory affairs", "Submissions, strategy"),
                ("Clinical affairs", "Trials, evidence, CRAs"), ("Commercial", "Sales, marketing, service"),
                ("Digital & data", "SaMD, analytics, cybersecurity")]),
    "20.2": dict(t="columns", cap="Career categories at a glance",
        cols=[("Technical", ["R&D / design engineer", "Manufacturing technician", "Validation engineer", "Biomedical engineer"]),
              ("Regulatory & clinical", ["Regulatory affairs associate", "Clinical research associate", "Quality assurance executive", "Vigilance specialist"]),
              ("Commercial & emerging", ["Product manager", "Application specialist", "Software validation (SaMD)", "Healthcare data analyst"])]),
    "20.3": dict(t="matrix", cap="Job roles by functional department",
        headers=["Department", "Entry role", "Mid-level", "Senior"],
        rows=[["R&D", "Design trainee", "Design engineer", "R&D manager / architect"],
              ["Manufacturing", "Production operator", "Process engineer", "Plant / operations head"],
              ["Quality", "QC analyst", "QA executive / auditor", "Quality head (PRRC)"],
              ["Regulatory", "RA trainee", "RA specialist", "RA manager / strategist"],
              ["Clinical", "CTC / site coordinator", "CRA", "Clinical affairs manager"],
              ["Commercial", "Sales executive", "Product specialist", "Business unit manager"]], rh=34),
    "20.4": dict(t="ladder", cap="Typical career progression ladder",
        steps=[("Years 0–2", "Trainee / associate — learn systems, GMP, documentation"),
               ("Years 2–5", "Specialist — own processes, audits, submissions"),
               ("Years 5–10", "Lead / manager — teams, budgets, strategy input"),
               ("Years 10+", "Head / director — business & regulatory strategy")],
        axis="Growth through certifications (RAC, CQA, PMP), domain depth and leadership"),
    "20.5": dict(t="hub", cap="Emerging MedTech career trends",
        center="Future-ready skills",
        spokes=[("SaMD & AI validation", "IEC 62304, ML testing"), ("Cybersecurity", "Device threat analysis"),
                ("Health data analytics", "FHIR, real-world evidence"), ("Robotics service", "Install & field support"),
                ("Regulatory intelligence", "Global harmonisation"), ("Sustainability", "Green design, EPR compliance")]),
}
