"""Figure specifications — Chapters 1–7 (43 figures)."""

SPECS_A = {
    # ---------------- Chapter 1 ----------------
    "1.1": dict(t="ladder", cap="Levels of invasiveness and associated risk",
        steps=[("Non-invasive", "Contact with intact skin only — BP cuffs, thermometers, ECG electrodes"),
               ("Minimally invasive", "Enter through natural orifices or needle puncture — catheters, endoscopes"),
               ("Invasive", "Penetrate body surfaces during procedures — surgical instruments"),
               ("Implantable", "Placed wholly or partly inside the body long-term — pacemakers, hip implants")],
        axis="Increasing invasiveness · increasing risk and regulatory control"),
    "1.2": dict(t="columns", cap="Duration-of-contact classification of medical devices",
        cols=[("Transient (< 60 min)", ["Examination gloves", "Surgical instruments", "Tongue depressors", "Lowest duration-related risk"]),
              ("Short-term (1–30 days)", ["Temporary catheters", "Wound dressings", "Infusion cannulae", "Moderate duration-related risk"]),
              ("Long-term (> 30 days)", ["Pacemakers", "Orthopaedic joint implants", "Coronary stents", "Highest duration-related risk"])]),
    "1.3": dict(t="decide", cap="US FDA device classification and controls flow",
        qs=[("Is the device low risk with well-understood safety profile?", "Class I — General controls; most exempt from 510(k)"),
            ("Is the device moderate risk, manageable with special controls?", "Class II — General + special controls; 510(k) clearance"),
            ("Does it sustain life or present high / novel risk?", "Class III — Premarket Approval (PMA) with clinical data")],
        final="Classify per 21 CFR panels and applicable guidance"),
    "1.4": dict(t="pyramid", cap="EU MDR classification pyramid (Regulation (EU) 2017/745)",
        levels=[("Class I", "Low risk — self-declaration for basic Class I; Is/Im/Ir need notified-body input"),
                ("Class IIa", "Low–moderate risk — notified body conformity assessment"),
                ("Class IIb", "Moderate–high risk — stricter notified body review"),
                ("Class III", "Highest risk — full quality system + design dossier review, clinical evidence")]),
    "1.5": dict(t="ladder", cap="India MDR 2017 risk ladder (Class A–D)",
        steps=[("Class A", "Low risk — absorbent cotton, tongue depressors; State Licensing Authority"),
               ("Class B", "Low–moderate risk — hypodermic needles, suction equipment; SLA"),
               ("Class C", "Moderate–high risk — ventilators, bone fixation plates; CDSCO (CLA)"),
               ("Class D", "High risk — heart valves, implantable pacemakers; CDSCO (CLA)")],
        axis="Increasing risk class · licensing shifts from State to Central authority"),
    "1.6": dict(t="hub", cap="Major categories of medical devices across care settings",
        center="Medical device categories",
        spokes=[("Diagnostic", "X-ray, MRI, IVD analysers"), ("Monitoring", "ECG, pulse oximeters"),
                ("Therapeutic", "Infusion pumps, lasers"), ("Surgical", "Instruments, staplers"),
                ("Implantable", "Stents, pacemakers"), ("Life-support", "Ventilators, dialysis"),
                ("Home-care", "Glucometers, nebulizers")]),
    "1.7": dict(t="zones", cap="Typical cleanroom personnel and material flow",
        rooms=[("Entry / Change", "Street garments removed", "Unclassified"),
               ("Gowning room", "Cleanroom garments donned", "+5 Pa"),
               ("Air shower / airlock", "Particle removal, pressure step", "+10 Pa"),
               ("ISO 8 zone", "Material staging, preparation", "+10 Pa"),
               ("ISO 7 zone", "Assembly and processing", "+15 Pa"),
               ("Packaging area", "Sealed product exits via pass-through", "+15 Pa")],
        legend="Air pressure increases toward the cleanest zones so that air always flows outward, keeping particles away from open product."),

    # ---------------- Chapter 2 ----------------
    "2.1": dict(t="hub", cap="The medical device industry ecosystem",
        center="Patient-centred device ecosystem",
        spokes=[("Manufacturers", "OEMs, contract manufacturers"), ("Regulators", "CDSCO, FDA, notified bodies"),
                ("Testing labs", "Biocompatibility, EMC, sterility"), ("Distributors", "Import, logistics, cold chain"),
                ("Healthcare providers", "Hospitals, clinics, home care"), ("Post-market services", "Maintenance, vigilance, recalls")]),
    "2.2": dict(t="flow", cap="Device manufacturing workflow from design to release",
        steps=[("Design & development", "Design controls, risk file"), ("Component sourcing", "Qualified suppliers"),
               ("Production", "Controlled environment"), ("In-process QC", "IPQC checkpoints"),
               ("Final testing", "Performance, safety"), ("Sterilization", "If required"),
               ("Packaging & labeling", "Sterile barrier, UDI"), ("Release & distribution", "Batch records reviewed")],
        cols=4),
    "2.3": dict(t="layers", cap="Structure of a medical device testing laboratory",
        bands=[("Accreditation & quality system", "ISO/IEC 17025 scope, NABL accreditation, documented methods"),
               ("Biological testing", "Biocompatibility (ISO 10993), sterility, bioburden, endotoxin"),
               ("Physical & mechanical testing", "Tensile, fatigue, dimensional, packaging integrity"),
               ("Electrical & EMC testing", "IEC 60601 electrical safety, electromagnetic compatibility"),
               ("Chemical & material analysis", "Extractables/leachables, material identity, residues")]),
    "2.4": dict(t="flow", cap="Pathway of a device through the healthcare delivery system",
        steps=[("Procurement", "Tenders, evaluation"), ("Incoming inspection", "Verification, asset tagging"),
               ("Clinical deployment", "Wards, OT, ICU, home"), ("User training", "Clinical & technical staff"),
               ("Maintenance", "Preventive & corrective"), ("Adverse event reporting", "MvPI / vigilance"),
               ("End-of-life", "Decommissioning, disposal")], cols=4),

    # ---------------- Chapter 3 ----------------
    "3.1": dict(t="ladder", cap="Levels of invasiveness and associated risk",
        steps=[("Non-invasive", "Skin-contact and external devices"), ("Minimally invasive", "Natural orifice / percutaneous"),
               ("Surgically invasive", "Operative penetration"), ("Implantable", "Long-term placement in the body")],
        axis="Increasing invasiveness · increasing evidence requirements"),
    "3.2": dict(t="columns", cap="Duration-based risk classification",
        cols=[("Transient (< 60 min)", ["Surgical instruments", "Examination gloves", "Risk level: LOW"]),
              ("Short-term (1–30 days)", ["Temporary catheters", "Wound dressings", "Risk level: MODERATE"]),
              ("Long-term (> 30 days)", ["Pacemakers", "Joint implants, stents", "Risk level: HIGH"])]),
    "3.3": dict(t="hub", cap="Criteria used worldwide to classify medical devices",
        center="Classification criteria",
        spokes=[("Invasiveness", "How far it enters the body"), ("Duration of contact", "Transient to permanent"),
                ("Anatomical site", "CNS & heart score higher"), ("Energy source", "Active vs passive"),
                ("Biological effect", "Absorbable, medicinal"), ("Intended purpose", "Diagnosis vs therapy")]),
    "3.4": dict(t="pyramid", cap="US FDA three-tier classification system",
        levels=[("Class I — General controls", "≈47% of device types; most 510(k)-exempt — bandages, hand instruments"),
                ("Class II — Special controls", "≈43% of types; 510(k) substantial equivalence — infusion pumps, imaging"),
                ("Class III — PMA", "≈10% of types; premarket approval with clinical evidence — heart valves")]),
    "3.5": dict(t="columns", cap="Examples of non-implantable Class III (high-risk) devices",
        cols=[("Life-sustaining external", ["Heart-lung machines", "External ventricular assist", "High-frequency ventilators"]),
              ("High-energy delivery", ["External defibrillators (some)", "Therapeutic ultrasound (HIFU)", "Certain laser systems"]),
              ("Critical drug delivery", ["Implanted-drug-path infusion", "Closed-loop insulin delivery", "Anaesthesia delivery (critical)"])]),
    "3.6": dict(t="ladder", cap="India MDR 2017 risk classification ladder",
        steps=[("Class A — Low", "Thermometers, tongue depressors"), ("Class B — Low-moderate", "Needles, suction equipment"),
               ("Class C — Moderate-high", "Ventilators, implants (some)"), ("Class D — High", "Heart valves, pacemakers")],
        axis="First Schedule rules assign class · higher class = Central Licensing Authority"),
    "3.7": dict(t="decide", cap="Worked classification decision path for a typical device",
        qs=[("Does the device only touch intact skin?", "Likely Class A / I — lowest controls"),
            ("Is body contact short-term via natural orifice or needle?", "Likely Class B / IIa — moderate controls"),
            ("Is it surgically invasive or long-term implanted?", "Class C / IIb–III — high controls"),
            ("Does it sustain life or contact heart / CNS?", "Class D / III — highest controls")],
        final="Confirm with jurisdiction rule set (MDR First Schedule / CFR / Annex VIII)"),

    # ---------------- Chapter 4 ----------------
    "4.1": dict(t="cycle", cap="The medical device lifecycle as a continuous loop",
        steps=["Concept & feasibility", "Design & development", "Verification & validation",
               "Regulatory approval", "Manufacturing", "Distribution & use", "Post-market surveillance", "Improvement / obsolescence"]),
    "4.2": dict(t="vflow", cap="Design control process (FDA 21 CFR 820.30 / ISO 13485)",
        steps=[("User needs", "Clinical problem, use environment, user profile"),
               ("Design inputs", "Measurable performance, safety and regulatory requirements"),
               ("Design process", "Architecture, prototyping, risk management (ISO 14971)"),
               ("Design outputs", "Drawings, specifications, DMR content"),
               ("Design verification", "Outputs meet inputs — bench and lab testing"),
               ("Design validation", "Device meets user needs — simulated / actual use"),
               ("Design transfer", "Specifications become production procedures")]),
    "4.3": dict(t="flow", cap="Prototype evolution pathway",
        steps=[("Proof of concept", "Core principle works"), ("Alpha prototype", "Looks-like / works-like"),
               ("Beta prototype", "Near-final materials"), ("Pilot units", "Production-equivalent"),
               ("Production device", "Validated processes")], cols=5),
    "4.4": dict(t="columns", cap="Verification versus validation",
        cols=[("Design verification", ["Question: did we build the device right?", "Outputs vs inputs", "Bench testing, inspection, analysis", "Example: tensile test meets spec"]),
              ("Design validation", ["Question: did we build the right device?", "Device vs user needs", "Simulated or actual use, usability studies", "Example: nurses infuse accurately in ICU"])]),
    "4.5": dict(t="vflow", cap="ISO 14971 risk management process",
        steps=[("Risk management plan", "Scope, responsibilities, criteria for acceptability"),
               ("Risk analysis", "Intended use, hazard identification, risk estimation"),
               ("Risk evaluation", "Compare estimated risks against criteria"),
               ("Risk control", "Inherent safety by design → protective measures → information for safety"),
               ("Residual risk evaluation", "Individual and overall benefit-risk"),
               ("Production & post-production", "Feedback loops update the risk file")]),
    "4.6": dict(t="matrix", cap="Global regulatory approval pathways compared",
        headers=["Aspect", "India (CDSCO)", "USA (FDA)", "EU (MDR)"],
        rows=[["Low risk", "Class A — SLA licence", "Class I — mostly exempt", "Class I — self-declare"],
              ["Moderate", "Class B/C licences", "Class II — 510(k)", "IIa/IIb — notified body"],
              ["High risk", "Class D — CLA licence", "Class III — PMA", "Class III — full review"],
              ["Clinical data", "Class C/D as required", "PMA: clinical data typically required", "III & implants: evidence"],
              ["Timeline", "6–12 months typical", "510(k) ~3–9 mo; PMA 1–3 yr", "6–18 months typical"]], rh=38),
    "4.7": dict(t="pyramid", cap="Manufacturing documentation pyramid",
        levels=[("Records (DHR)", "Evidence of what was made — batch records, test results"),
                ("Work instructions & SOPs", "Step-by-step operational detail"),
                ("Procedures & DMR", "Device master record: specs, methods, acceptance criteria"),
                ("Quality manual & policy", "Top-level commitments and QMS structure")],
        mono=True, axis=None),
    "4.8": dict(t="cycle", cap="Post-market surveillance feedback cycle",
        steps=["Collect field data", "Complaints & vigilance", "Trend analysis", "Risk file update",
               "CAPA where needed", "Design / process change", "Regulatory reporting"]),

    # ---------------- Chapter 5 ----------------
    "5.1": dict(t="hub", cap="Core functions of a quality management system",
        center="QMS core functions",
        spokes=[("Document control", "Approved, current, retrievable"), ("Management responsibility", "Policy, objectives, review"),
                ("Resource management", "People, infrastructure"), ("Product realization", "Design through delivery"),
                ("Measurement & analysis", "Audits, data, monitoring"), ("Improvement", "CAPA, preventive thinking")]),
    "5.2": dict(t="layers", cap="ISO 13485:2016 clause structure",
        bands=[("Clauses 1–3 — Scope, references, terms", "Foundation and vocabulary of the standard"),
               ("Clause 4 — Quality management system", "General requirements, documentation, medical device file"),
               ("Clause 5 — Management responsibility", "Policy, planning, responsibility, management review"),
               ("Clause 6 — Resource management", "Personnel, infrastructure, work environment, contamination control"),
               ("Clause 7 — Product realization", "Planning, design & development, purchasing, production, servicing"),
               ("Clause 8 — Measurement, analysis, improvement", "Feedback, complaints, audits, nonconformity, CAPA")]),
    "5.3": dict(t="pyramid", cap="QMS documentation hierarchy",
        levels=[("Level 4 — Records & forms", "Objective evidence: batch records, training records, test data"),
                ("Level 3 — Work instructions", "Task-level detail for operators and inspectors"),
                ("Level 2 — Procedures (SOPs)", "Who does what, when and how across processes"),
                ("Level 1 — Quality manual", "Policy, scope, process map of the whole QMS")],
        mono=True),
    "5.4": dict(t="vflow", cap="Risk-based decision making in the QMS",
        steps=[("Identify the decision or change", "Supplier, process, design or resource decision"),
               ("? Could it affect product safety or performance?", "Consider severity and probability"),
               ("Assess risk using ISO 14971 principles", "Estimate, evaluate against criteria"),
               ("Apply proportionate controls", "Validation depth, sampling, review level scale with risk"),
               ("Record rationale and monitor", "Feedback into the risk file and CAPA system")]),
    "5.5": dict(t="flow", cap="CAPA process from problem to closure",
        steps=[("Problem detected", "Complaint, audit, NC, trend"), ("Containment", "Immediate correction"),
               ("Root cause analysis", "5-Why, fishbone, data"), ("Action plan", "Corrective & preventive"),
               ("Implementation", "Changes executed"), ("Effectiveness check", "Did it work?"),
               ("Closure & records", "Documented evidence")], cols=4),

    # ---------------- Chapter 6 ----------------
    "6.1": dict(t="zones", cap="Basic cleanroom layout with pressure cascade",
        rooms=[("Entry", "Personnel entrance", "Ambient"),
               ("Gowning", "Garment change", "+5 Pa"),
               ("Airlock", "Pressure step", "+10 Pa"),
               ("ISO 8 area", "Material prep", "+10 Pa"),
               ("ISO 7 core", "Open-product work", "+15 Pa")],
        legend="HEPA-filtered air enters at ceiling level; pressure is highest where product is most exposed."),
    "6.2": dict(t="pyramid", cap="ISO 14644-1 cleanroom classes used in device manufacturing",
        levels=[("ISO 8", "≤ 3,520,000 particles/m³ (≥0.5 µm) — general assembly, packaging"),
                ("ISO 7", "≤ 352,000 particles/m³ — device assembly, gowning to cleaner zones"),
                ("ISO 6", "≤ 35,200 particles/m³ — higher-grade processing"),
                ("ISO 5", "≤ 3,520 particles/m³ — laminar-flow hoods, critical/aseptic work")]),
    "6.3": dict(t="columns", cap="Laminar (unidirectional) versus turbulent airflow",
        cols=[("Unidirectional (laminar)", ["Parallel air streams at uniform velocity (≈0.45 m/s)", "Sweeps particles straight to returns", "Used at critical work zones (ISO 5)", "Higher energy and filter cost"]),
              ("Non-unidirectional (turbulent)", ["Mixed dilution airflow", "Cleanliness via air-change rate (ACH)", "Used for ISO 7–8 background areas", "More economical to run"])]),
    "6.4": dict(t="cycle", cap="HVAC air-handling cycle for a cleanroom",
        steps=["Fresh-air intake", "Pre-filtration", "Conditioning (T & RH)", "HEPA filtration",
               "Ceiling supply", "Room sweep", "Low-level return", "Recirculation"]),
    "6.5": dict(t="flow", cap="Cleanroom gowning sequence",
        steps=[("Remove street items", "Jewellery, cosmetics"), ("Hand hygiene", "Wash & sanitise"),
               ("Bouffant & mask", "Hair and beard cover"), ("Coverall", "Without touching floor"),
               ("Boots / overshoes", "Seated on bench"), ("Goggles & gloves", "Gloves last, sanitised"),
               ("Self-check mirror", "No exposed skin/hair"), ("Enter via airlock", "Pressure-controlled")],
        cols=4),
    "6.6": dict(t="vflow", cap="Environmental monitoring programme",
        steps=[("Define monitoring plan", "Locations, frequencies, alert and action limits"),
               ("Measure", "Particles, viable counts (settle/contact plates), pressure, T/RH, air velocity"),
               ("? Result exceeds alert or action limit?", "Compare with documented limits"),
               ("Investigate & correct", "Root cause, cleaning, requalification as needed"),
               ("Trend & review", "Periodic reports feed management review and requalification")],
        edge_labels={2: "YES"}),
    "6.7": dict(t="decide", cap="Choosing a sterilization method",
        qs=[("Is the product heat- and moisture-stable?", "Steam autoclave — 121–134°C, most economical"),
            ("Is it heat-sensitive but gas-permeable?", "Ethylene oxide — low temp, requires aeration"),
            ("Is dense packaging / no aeration time acceptable?", "Gamma / e-beam radiation — high penetration"),
            ("Is it a liquid or heat-labile fluid path?", "Sterile filtration / aseptic processing")],
        final="Validate the chosen method (ISO 11135 / 11137 / 17665)"),

    # ---------------- Chapter 7 ----------------
    "7.1": dict(t="hub", cap="Classification of biomaterials used in devices",
        center="Biomaterials",
        spokes=[("Metals", "SS 316L, titanium, Co-Cr, nitinol"), ("Polymers", "PE, PP, PVC, PEEK, silicone"),
                ("Ceramics", "Alumina, zirconia, hydroxyapatite"), ("Composites", "CFR-PEEK, coated metals"),
                ("Natural materials", "Collagen, chitosan, silk"), ("Bioresorbables", "PLA, PGA, Mg alloys")]),
    "7.2": dict(t="matrix", cap="Metallic biomaterials and typical applications",
        headers=["Metal", "Key properties", "Typical applications"],
        rows=[["SS 316L", "Economical, strong, corrosion-resistant", "Bone plates, screws, instruments"],
              ["Titanium & alloys", "Light, biocompatible, osseointegrates", "Dental & orthopaedic implants"],
              ["Cobalt-chromium", "Hard, wear-resistant", "Joint bearing surfaces, stents"],
              ["Nitinol (Ni-Ti)", "Superelastic, shape memory", "Self-expanding stents, guidewires"],
              ["Tantalum", "Highly inert, porous forms", "Bone-ingrowth structures"]], rh=38),
    "7.3": dict(t="matrix", cap="Common medical polymers compared",
        headers=["Polymer", "Character", "Typical uses"],
        rows=[["PVC (plasticised)", "Flexible, clear, weldable", "Tubing, blood bags, IV sets"],
              ["Polyethylene (UHMWPE)", "Tough, low friction", "Joint bearing surfaces"],
              ["Polypropylene", "Chemical resistance, autoclavable", "Syringes, sutures, meshes"],
              ["Silicone", "Flexible, thermally stable, inert", "Catheters, seals, implants"],
              ["PEEK", "High strength, radiolucent", "Spinal cages, trauma implants"],
              ["Polycarbonate", "Clear, impact-resistant", "Connectors, oxygenator housings"]], rh=36),
    "7.4": dict(t="columns", cap="Ceramic biomaterials by biological response",
        cols=[("Bioinert", ["Alumina (Al₂O₃)", "Zirconia (ZrO₂)", "Minimal tissue interaction", "Bearing surfaces, dental crowns"]),
              ("Bioactive", ["Bioglass", "Glass-ceramics", "Bond chemically to bone", "Coatings, bone grafts"]),
              ("Bioresorbable", ["Tricalcium phosphate", "Some calcium sulphates", "Gradually replaced by bone", "Bone void fillers"])]),
    "7.5": dict(t="matrix", cap="ISO 10993-1 biological evaluation test selection (simplified)",
        headers=["Contact / duration", "Cytotoxicity", "Sensitization", "Irritation", "Systemic toxicity", "Implantation"],
        rows=[["Surface, transient", "●", "●", "●", "—", "—"],
              ["Surface, prolonged", "●", "●", "●", "○", "—"],
              ["External communicating", "●", "●", "●", "●", "○"],
              ["Implant, short-term", "●", "●", "●", "●", "●"],
              ["Implant, long-term", "●", "●", "●", "●", "●"]],
        rh=32, wide_first=True),
}
