"""Figure specifications — Chapters 8–14 (67 figures)."""

SPECS_B = {
    # ---------------- Chapter 8 ----------------
    "8.1": dict(t="formulabox", cap="Stress — the internal force carried per unit area",
        lines=[("σ = F / A", "Stress (σ, in pascal) equals applied force F divided by cross-sectional area A")]),
    "8.2": dict(t="formulabox", cap="Strain and elastic modulus",
        lines=[("ε = ΔL / L₀", "Strain (ε, dimensionless) is the change in length relative to original length"),
               ("E = σ / ε", "Young's modulus E — material stiffness in the elastic region (Hooke's law)")]),
    "8.3": dict(t="curve", cap="Stress–strain curve of a typical implant material",
        x="Strain (ΔL/L₀)", y="Stress (MPa)"),
    "8.4": dict(t="columns", cap="Mechanical forces acting on a hip implant during gait",
        cols=[("Compression", ["Body weight pressing along the stem axis", "Peak 3–5× body weight when walking", "Stem and cup must resist crushing"]),
              ("Bending & shear", ["Off-axis loading of femoral neck", "Cyclic bending each step", "Classic fatigue-fracture site"]),
              ("Torsion & friction", ["Rotation during turning, stair climb", "Articulating friction at head–cup", "Drives wear-particle generation"])]),
    "8.5": dict(t="columns", cap="Principal wear mechanisms at bearing surfaces",
        cols=[("Adhesive wear", ["Micro-welding of contacting asperities", "Material transfer between surfaces", "Dominant in metal-on-metal pairs"]),
              ("Abrasive wear", ["Hard asperities or third-body particles plough the softer surface", "Scratching, cutting grooves", "Bone cement debris accelerates it"]),
              ("Fatigue wear", ["Repeated subsurface stress cycles", "Cracks nucleate and spall (delamination)", "Seen in polyethylene liners"])]),
    "8.6": dict(t="hub", cap="What biocompatibility must guarantee",
        center="Biocompatibility",
        spokes=[("No cytotoxicity", "Cells survive contact"), ("No sensitization", "No allergic response"),
                ("No irritation", "Local tissue tolerance"), ("Haemocompatible", "No clotting, no haemolysis"),
                ("No systemic toxicity", "Acute through chronic"), ("Stable long-term", "No harmful degradation")]),
    "8.7": dict(t="vflow", cap="Biological evaluation method under ISO 10993-1",
        steps=[("Characterise the device", "Materials, additives, processing residues, contact type and duration"),
               ("Gap analysis of existing data", "Literature, prior testing, clinical history of materials"),
               ("? Are all biological endpoints already addressed?", "Endpoint table of ISO 10993-1"),
               ("Plan and run only needed tests", "Cytotoxicity first (ISO 10993-5), then per endpoint table"),
               ("Biological evaluation report", "Overall risk conclusion by qualified assessor")],
        edge_labels={2: "NO"}),

    # ---------------- Chapter 9 ----------------
    "9.1": dict(t="layers", cap="Design control framework — the governing elements",
        bands=[("Design & development planning", "Stages, responsibilities, reviews defined up front"),
               ("Design inputs ← user needs", "Measurable requirements from clinical need and regulation"),
               ("Design outputs", "Specifications, drawings, software, labeling"),
               ("Reviews · verification · validation", "Formal gates proving outputs meet inputs and needs"),
               ("Design transfer & DHF", "Production handover; design history file as evidence")]),
    "9.2": dict(t="flow", cap="Translating user needs into engineering design inputs",
        steps=[("User need", "“Easy one-hand use”"), ("Contextual inquiry", "Observe real users"),
               ("Requirement", "Operable with one hand, gloved"), ("Specification", "Force < 22 N; grip Ø 28–34 mm"),
               ("Acceptance test", "Verification protocol")], cols=5),
    "9.3": dict(t="cycle", cap="Usability engineering lifecycle (IEC 62366-1)",
        steps=["Use specification", "Hazard-related use scenarios", "Interface design", "Formative evaluation",
               "Refinement", "Summative validation", "Post-market use data"]),
    "9.4": dict(t="flow", cap="Prototype development stages",
        steps=[("Concept sketch", "Idea capture"), ("3D-printed mock-up", "Form & fit"),
               ("Functional prototype", "Works-like"), ("Design-freeze unit", "Looks-like & works-like"),
               ("Pilot production", "Process-proven")], cols=5),
    "9.5": dict(t="columns", cap="Verification versus validation in design controls",
        cols=[("Verification — built right?", ["Design outputs vs design inputs", "Bench tests, inspections, analyses", "Objective specs, instrumented data", "Performed throughout development"]),
              ("Validation — right device?", ["Final device vs user needs", "Simulated / actual use, usability", "Production-equivalent units", "Late-stage, before launch"])]),
    "9.6": dict(t="vflow", cap="Design transfer into manufacturing",
        steps=[("Approved design outputs", "Frozen specifications and drawings"),
               ("Process development", "Tooling, fixtures, process instructions"),
               ("Process validation (IQ/OQ/PQ)", "Equipment installed, operating windows, performance proven"),
               ("Pilot builds & first article", "Production-line units verified against DMR"),
               ("Full production release", "Trained operators, controlled documents")]),
    "9.7": dict(t="pyramid", cap="Design documentation hierarchy",
        levels=[("Records", "Test reports, review minutes, traceability matrices"),
                ("DHF — design history file", "Evidence the design was developed under controls"),
                ("DMR — device master record", "The full recipe for making the device"),
                ("Technical file / dossier", "Regulatory summary for submission")],
        mono=True),

    # ---------------- Chapter 10 ----------------
    "10.1": dict(t="flow", cap="End-to-end medical device production flow",
        steps=[("Incoming materials", "Supplier COA, inspection"), ("Component production", "Molding, machining"),
               ("Cleaning", "Particulate & residue control"), ("Assembly", "Controlled environment"),
               ("In-process QC", "Checkpoints, SPC"), ("Sterilization", "EO / gamma / steam"),
               ("Final packaging", "Sterile barrier system"), ("Release", "Batch record review")], cols=4),
    "10.2": dict(t="flow", cap="Injection molding cycle",
        steps=[("Clamping", "Mold halves close"), ("Injection", "Molten polymer fills cavity"),
               ("Packing & holding", "Pressure compensates shrinkage"), ("Cooling", "Part solidifies"),
               ("Ejection", "Part released"), ("Inspection", "Dimensional & visual QC")], cols=3),
    "10.3": dict(t="zones", cap="Medical tubing extrusion line",
        rooms=[("Hopper & dryer", "Resin conditioning", "Feed"),
               ("Extruder barrel", "Melt & convey", "180–240°C"),
               ("Die head", "Forms tube profile", "Sizing"),
               ("Vacuum calibration", "Holds OD tolerance", "Cooling bath"),
               ("Laser gauging", "Continuous OD/wall check", "QC"),
               ("Puller & cutter", "Speed sets wall", "Spool/cut")],
        legend="Line speed, melt temperature and vacuum are the critical process parameters recorded in the batch record."),
    "10.4": dict(t="flow", cap="CNC machining workflow for implant components",
        steps=[("CAD model", "Design geometry"), ("CAM programming", "Toolpaths, feeds, speeds"),
               ("Machine setup", "Fixturing, tool offsets"), ("Machining", "Milling / turning"),
               ("Deburr & finish", "Edge and surface work"), ("CMM inspection", "Dimensional report")], cols=3),
    "10.5": dict(t="flow", cap="Metal processing workflow from bar stock to implant",
        steps=[("Material certification", "Mill certs, traceability"), ("Cutting / forging", "Near-net shape"),
               ("Machining", "Precision features"), ("Heat treatment", "Strength, stress relief"),
               ("Surface finishing", "Electropolish, anodise, blast"), ("Cleaning & passivation", "ASTM A967"),
               ("Marking (UDI)", "Laser marking"), ("Final inspection", "Visual + dimensional")], cols=4),
    "10.6": dict(t="zones", cap="Assembly line layout inside the cleanroom",
        rooms=[("Kitting", "Components staged", "ISO 8"),
               ("Sub-assembly", "Bonding, welding", "ISO 8"),
               ("Final assembly", "Open-product zone", "ISO 7"),
               ("In-line testing", "Function checks", "ISO 7"),
               ("Primary packaging", "Sterile barrier sealing", "ISO 7")],
        legend="Product moves toward progressively cleaner zones until sealed in its sterile barrier."),
    "10.7": dict(t="profile", cap="Ethylene oxide sterilization cycle profile",
        x="Cycle time (≈ 12–24 h) →", y="Chamber condition",
        phases=[("Preconditioning", 30, 3), ("Vacuum & leak test", 15, 1),
                ("Humidification", 45, 2), ("EO gas injection", 90, 1.5),
                ("Exposure (dwell)", 90, 4), ("Gas evacuation", 25, 1.5),
                ("Air washes", 35, 2), ("Aeration", 20, 5)]),
    "10.8": dict(t="labelcard", cap="Example medical device label content",
        title="ACME MEDICAL — INFUSION SET, STERILE EO",
        fields=[("REF (catalogue no.)", "IS-2030-20G"), ("LOT / Batch", "LOT4521"),
                ("Manufacture date", "2026-01"), ("Use-by date", "2029-01"),
                ("Sterile EO · Single use", "Do not resterilize"), ("Manufacturer", "ACME Medical Devices Pvt. Ltd., Chennai")]),
    "10.9": dict(t="vflow", cap="In-process quality control decision flow",
        steps=[("Process step completed", "Assembly, molding, welding…"),
               ("IPQC check per control plan", "Sampling, measurement, test method"),
               ("? Result within specification?", "Compare with acceptance criteria"),
               ("Continue to next operation", "Record results in batch record"),
               ("If out of spec: quarantine & NCR", "Segregate, disposition (rework / scrap), investigate — feed CAPA")],
        edge_labels={2: "YES"}),
    "10.10": dict(t="zones", cap="Medical device factory zoning concept",
        rooms=[("Warehouse", "Raw materials, quarantine", "Ambient"),
               ("Production", "Molding, machining halls", "Controlled"),
               ("Cleanroom suite", "Assembly & packaging", "ISO 7/8"),
               ("Sterilization", "EO chamber / interface", "Dedicated"),
               ("Finished goods", "Released stock, dispatch", "Ambient")],
        legend="One-way material flow prevents mix-ups between quarantined, in-process and released product."),

    # ---------------- Chapter 11 ----------------
    "11.1": dict(t="flow", cap="Where quality control sits in the manufacturing flow",
        steps=[("Incoming QC", "Materials & components"), ("In-process QC", "During production"),
               ("Final QC", "Finished device testing"), ("Batch release", "QA review of all records")], cols=4),
    "11.2": dict(t="vflow", cap="Tensile testing of device components",
        steps=[("Prepare specimen", "Standard geometry (e.g., ASTM D638), conditioning"),
               ("Mount in grips", "Aligned, slack-free, gauge length set"),
               ("Pull at constant rate", "Load cell records force vs elongation"),
               ("Record curve to failure", "Yield, ultimate strength, elongation at break"),
               ("Compare with specification", "Pass/fail against acceptance criteria")]),
    "11.3": dict(t="hub", cap="Electrical safety tests for medical electrical equipment (IEC 60601-1)",
        center="Electrical safety testing",
        spokes=[("Earth continuity", "Protective earth resistance"), ("Insulation resistance", "Between circuits & parts"),
                ("Leakage currents", "Earth, touch, patient leakage"), ("Dielectric strength", "High-potential withstand"),
                ("Applied-part tests", "Type B / BF / CF limits"), ("EMC (IEC 60601-1-2)", "Emissions & immunity")]),
    "11.4": dict(t="vflow", cap="Sterilization validation workflow (e.g., EO per ISO 11135)",
        steps=[("Define product families & loads", "Worst-case configuration chosen"),
               ("Install & qualify equipment (IQ/OQ)", "Chamber mapping, sensors calibrated"),
               ("Microbiological PQ", "Half-cycle / overkill with biological indicators"),
               ("Physical PQ", "Full cycles confirm parameters and residuals (ISO 10993-7)"),
               ("Routine control & revalidation", "Parametric release limits, annual review")]),
    "11.5": dict(t="flow", cap="QC documentation flow to batch release",
        steps=[("Test protocols", "Approved methods"), ("Raw data & results", "Instruments, worksheets"),
               ("Certificates of analysis", "Per lot summary"), ("Nonconformance reports", "If deviations occur"),
               ("Device history record", "Complete batch evidence"), ("QA release decision", "Authorised signatory")], cols=3),

    # ---------------- Chapter 12 ----------------
    "12.1": dict(t="hub", cap="Fundamental goals of medical device regulation",
        center="Why regulate devices?",
        spokes=[("Patient safety", "Prevent harm from unsafe devices"), ("Performance assurance", "Devices do what they claim"),
                ("Quality manufacturing", "Consistent, controlled production"), ("Truthful information", "Labeling & claims control"),
                ("Market surveillance", "Detect & act on field problems"), ("Innovation pathway", "Predictable route to market")]),
    "12.2": dict(t="pyramid", cap="India MDR 2017 risk-based classification",
        levels=[("Class A", "Low risk — SLA licence (Form MD-5) — e.g., absorbent cotton"),
                ("Class B", "Low–moderate — SLA licence — e.g., hypodermic needles"),
                ("Class C", "Moderate–high — CLA licence (Form MD-9) — e.g., ventilators"),
                ("Class D", "High risk — CLA licence — e.g., heart valves, pacemakers")]),
    "12.3": dict(t="vflow", cap="India approval process for Class C/D devices",
        steps=[("Appoint authorised agent (if foreign)", "Wholesale licence holder in India"),
               ("Compile technical documentation", "Device master file, plant master file, ISO 13485 certificate"),
               ("Apply on SUGAM portal", "Form MD-7 (import: MD-14) with fees"),
               ("? CDSCO query / audit round?", "Respond to queries; possible inspection"),
               ("Licence granted (MD-9 / MD-15)", "Valid subject to conditions and vigilance duties")],
        edge_labels={3: "Resolve"}),
    "12.4": dict(t="pyramid", cap="US FDA three-tier classification",
        levels=[("Class I", "General controls — registration, listing, GMP; most 510(k)-exempt"),
                ("Class II", "General + special controls — usually 510(k) premarket notification"),
                ("Class III", "Premarket approval (PMA) — valid scientific evidence incl. clinical data")]),
    "12.5": dict(t="decide", cap="FDA regulatory pathway decision tree",
        qs=[("Is there a legally marketed predicate with same intended use?", "510(k) — demonstrate substantial equivalence"),
            ("Novel low-moderate risk device without predicate?", "De Novo — risk-based classification request"),
            ("Class III / life-sustaining / high risk?", "PMA — full clinical evidence review"),
            ("Rare condition (< 8,000 US patients/yr)?", "HDE — humanitarian device exemption")],
        final="Confirm pathway in pre-submission (Q-Sub) meeting with FDA"),
    "12.6": dict(t="pyramid", cap="EU MDR four-tier classification",
        levels=[("Class I", "Self-declaration (basic); Is/Im/Ir need notified body for specific aspects"),
                ("Class IIa", "Notified body review of technical documentation (sampling)"),
                ("Class IIb", "Notified body review incl. clinical evaluation scrutiny"),
                ("Class III", "Design dossier examination, clinical evidence, expert panels")]),
    "12.7": dict(t="vflow", cap="EU MDR clinical evaluation process",
        steps=[("Clinical evaluation plan (CEP)", "Scope, GSPRs addressed, state of the art"),
               ("Identify & appraise data", "Own investigations, equivalent device data, literature"),
               ("Analyse benefit-risk", "Against acceptance criteria from the CEP"),
               ("Clinical evaluation report (CER)", "Signed by qualified evaluators"),
               ("PMCF loop", "Post-market clinical follow-up updates the CER through life")]),
    "12.8": dict(t="timeline", cap="Typical CE marking journey",
        events=[("Month 0", "QMS & technical file ready"), ("Month 1–2", "Notified body application & contract"),
                ("Month 3–8", "Documentation review & audit"), ("Month 8–12", "Findings closed, certificate issued"),
                ("Month 12+", "Declaration of Conformity, CE mark affixed, EUDAMED registration")]),
    "12.9": dict(t="labelcard", cap="UDI-labelled device — data elements",
        title="CARDIOFLOW STENT SYSTEM — STERILE EO",
        fields=[("UDI-DI (device identifier)", "(01) 08901234567894"),
                ("Production date (11)", "2026-01-01"), ("Expiry date (17)", "2029-01-01"),
                ("Lot number (10)", "LOT4521"), ("GMDN / category", "Coronary artery stent"),
                ("Manufacturer", "CardioFlow Devices Ltd.")]),
    "12.10": dict(t="matrix", cap="Vigilance reporting timelines compared",
        headers=["Event type", "India (MvPI/CDSCO)", "USA (FDA MDR)", "EU (MDR Art. 87)"],
        rows=[["Death / serious injury", "Within 15 days", "30 days (5-day for urgent)", "15 days (10 if death)"],
              ["Serious public-health threat", "48 hours", "5 work days", "2 days"],
              ["Malfunction (could cause harm)", "30 days", "30 days", "15 days"],
              ["Periodic summary", "PSUR as required", "Annual reports (PMA)", "PSUR (IIa+) / SSCP"]], rh=40),

    # ---------------- Chapter 13 ----------------
    "13.1": dict(t="timeline", cap="Evolution of software in healthcare",
        events=[("1960s–80s", "Hospital information systems"), ("1990s", "Software embedded in devices"),
                ("2000s", "Standalone diagnostic software"), ("2013", "IMDRF defines SaMD"),
                ("2017+", "AI/ML devices cleared"), ("2020s", "Digital therapeutics & adaptive AI")]),
    "13.2": dict(t="columns", cap="SaMD versus software in a medical device (SiMD)",
        cols=[("SaMD", ["Software IS the medical device", "Runs on general-purpose platforms (phone, PC, cloud)", "Example: retinal-image diagnostic app", "Regulated on its own merit"]),
              ("SiMD (embedded)", ["Software inside a hardware device", "Controls or supports the hardware", "Example: infusion-pump firmware", "Regulated with the parent device"])]),
    "13.3": dict(t="decide", cap="Is the software a medical device?",
        qs=[("Does it only store, transfer or display data unchanged?", "Not a medical device (data conduit)"),
            ("Is it for general wellness only (fitness, lifestyle)?", "Usually not regulated as a device"),
            ("Does it analyse data to diagnose, prevent, monitor or treat?", "SaMD — classify by risk"),
            ("Does it drive or control a hardware device?", "SiMD — part of parent device")],
        final="Document the qualification rationale (MDCG 2019-11 / FDA guidance)"),
    "13.4": dict(t="hub", cap="Global SaMD regulatory framework alignment (IMDRF)",
        center="IMDRF SaMD framework",
        spokes=[("N10 — Definitions", "Common SaMD vocabulary"), ("N12 — Risk categories", "I–IV by state & significance"),
                ("N23 — QMS", "SaMD quality management"), ("N41 — Clinical evaluation", "Valid clinical association"),
                ("FDA adoption", "Pre-cert & guidance lineage"), ("EU MDR Rule 11", "Software classification rule")]),
    "13.5": dict(t="matrix", cap="Software classification across jurisdictions",
        headers=["Healthcare situation", "Inform decisions", "Drive management", "Treat / diagnose"],
        rows=[["Non-serious condition", "IMDRF I — lowest", "IMDRF I–II", "IMDRF II"],
              ["Serious condition", "IMDRF II", "IMDRF II–III", "IMDRF III"],
              ["Critical condition", "IMDRF II–III", "IMDRF III", "IMDRF IV — highest"]], rh=38),
    "13.6": dict(t="cycle", cap="AI/ML device development and validation lifecycle",
        steps=["Data acquisition", "Curation & labelling", "Model training", "Analytical validation",
               "Clinical validation", "Deployment", "Real-world monitoring", "Retraining (controlled)"]),
    "13.7": dict(t="matrix", cap="AI/ML device approval approaches compared",
        headers=["Aspect", "USA (FDA)", "EU (MDR + AI Act)", "India (CDSCO)"],
        rows=[["Framework", "PCCP for planned changes", "MDR Rule 11 + AI Act risk tiers", "SaMD under MDR 2017"],
              ["Adaptive algorithms", "Allowed with locked change plan", "Case-by-case, conformity reassessed", "Emerging guidance"],
              ["Transparency", "Model cards encouraged", "AI Act mandates documentation", "Under development"]], rh=44),
    "13.8": dict(t="layers", cap="Cybersecurity framework for medical software",
        bands=[("Governance & risk management", "Security integrated with ISO 14971 risk process"),
               ("Secure design", "Threat modelling, least privilege, secure defaults"),
               ("Secure implementation", "Code review, dependency management, SBOM"),
               ("Verification & penetration testing", "Vulnerability scanning, fuzzing, pen tests"),
               ("Post-market security", "Monitoring, coordinated disclosure, patch management")]),
    "13.9": dict(t="vmodel", cap="IEC 62304 software lifecycle V-model",
        left=["Software requirements analysis", "Architectural design", "Detailed design", "Unit implementation"],
        right=["Unit verification", "Integration testing", "System testing", "Release & requirements validation"],
        bottom="Traceability maintained across every level"),
    "13.10": dict(t="matrix", cap="Software V&V traceability matrix (illustrative)",
        headers=["Requirement", "Design element", "Test case", "Result"],
        rows=[["REQ-01 Dose limit alarm", "Module ALM-2", "TC-014", "✓"],
              ["REQ-02 Data encryption", "Module SEC-1", "TC-021", "✓"],
              ["REQ-03 Offline mode", "Module SYNC-3", "TC-034", "✓"],
              ["REQ-04 Audit trail", "Module LOG-1", "TC-042", "✓"]], rh=32),
    "13.11": dict(t="pyramid", cap="SaMD documentation pyramid",
        levels=[("Records & logs", "Test evidence, anomaly lists, release notes"),
                ("Lifecycle documents", "IEC 62304 plans, architecture, V&V reports"),
                ("Risk & usability files", "ISO 14971 + IEC 62366-1 evidence"),
                ("Regulatory submission", "510(k)/CE technical documentation summary")],
        mono=True),
    "13.12": dict(t="bars", cap="Where approved AI/ML medical devices concentrate (indicative shares)",
        items=[("Radiology imaging", 76, "≈ 3 of every 4 approvals"), ("Cardiology", 10, "ECG & monitoring analytics"),
               ("Neurology", 5, "Stroke triage, EEG"), ("Ophthalmology", 4, "Diabetic retinopathy"),
               ("Other specialties", 5, "Pathology, dermatology…")]),
    "13.13": dict(t="hub", cap="Ethical framework for AI in medical devices",
        center="Trustworthy medical AI",
        spokes=[("Beneficence", "Improves patient outcomes"), ("Non-maleficence", "Fails safely, no harm"),
                ("Autonomy", "Clinician & patient oversight"), ("Justice & equity", "Works across populations"),
                ("Transparency", "Explainable decisions"), ("Accountability", "Clear responsibility chain")]),
    "13.14": dict(t="vflow", cap="Preventing algorithmic bias across the model lifecycle",
        steps=[("Representative data collection", "Demographics, devices, sites reflect intended population"),
               ("Bias audit of training data", "Label quality, subgroup coverage, proxy variables"),
               ("Subgroup performance analysis", "Sensitivity/specificity reported per subgroup — mandatory"),
               ("Mitigation & re-training", "Re-weighting, augmentation, threshold tuning"),
               ("Continuous real-world monitoring", "Drift detection and periodic fairness re-checks")]),

    # ---------------- Chapter 14 ----------------
    "14.1": dict(t="decide", cap="Is a new clinical investigation required?",
        qs=[("Can equivalence to an existing device be demonstrated?", "Leverage equivalent device clinical data"),
            ("Is sufficient literature + performance data available?", "Literature-route clinical evaluation"),
            ("Is the device high-risk, novel or implantable?", "Clinical investigation usually required")],
        final="Document the route in the clinical evaluation plan"),
    "14.2": dict(t="pyramid", cap="Hierarchy of clinical evidence",
        levels=[("Case reports & expert opinion", "Lowest weight — hypothesis generating"),
                ("Observational studies & registries", "Real-world signals, PMCF backbone"),
                ("Non-randomised controlled studies", "Comparative but bias-prone"),
                ("RCTs & systematic reviews", "Highest weight — confirmatory evidence")],
        mono=True, axis=("LOWER WEIGHT", "HIGHER WEIGHT")),
    "14.3": dict(t="vflow", cap="Clinical evaluation report (CER) development",
        steps=[("Clinical evaluation plan", "Questions, GSPRs, state of the art defined"),
               ("Literature search protocol", "Databases, terms, inclusion/exclusion criteria"),
               ("Appraise & weight evidence", "Relevance and methodological quality scoring"),
               ("Analyse against acceptance criteria", "Safety, performance, benefit-risk"),
               ("Write & sign CER", "Qualified evaluators; feeds notified-body review"),
               ("Update with PMS / PMCF data", "Living document across the lifecycle")]),
    "14.4": dict(t="vflow", cap="CDSCO clinical investigation approval (India)",
        steps=[("Protocol & investigator brochure", "Per MDR 2017 Seventh Schedule & GCP"),
               ("Ethics committee approval", "Registered EC for each site"),
               ("Apply on SUGAM (Form MD-22)", "CDSCO reviews application"),
               ("? Subject Expert Committee queries?", "Respond / amend protocol"),
               ("Permission granted (MD-23)", "Register on CTRI before first enrolment"),
               ("Conduct with safety reporting", "SAE reporting & compensation per rules")],
        edge_labels={3: "Resolve"}),
    "14.5": dict(t="columns", cap="FDA clinical study pathways",
        cols=[("Significant-risk IDE", ["FDA + IRB approval required", "Full IDE application", "Implants, life-sustaining devices", "Most PMA-track studies"]),
              ("Non-significant-risk IDE", ["IRB approval only (abbreviated IDE)", "Sponsor keeps records/reports", "Lower-risk investigations", "Many 510(k)-track studies"]),
              ("Exempt studies", ["Certain diagnostics with leftover samples", "Consumer preference / minor mods", "No IDE needed", "GCP still applies"])]),
    "14.6": dict(t="timeline", cap="EU MDR clinical investigation timeline (Articles 62–80)",
        events=[("Day 0", "Application via EUDAMED"), ("Day 10", "Validation check complete"),
                ("Day 45", "Member state assessment"), ("Day 45+", "Approval (may extend +20 for experts)"),
                ("Ongoing", "SAE reporting & annual updates"), ("End", "Clinical investigation report")]),
    "14.7": dict(t="flow", cap="Clinical development pathway of a device",
        steps=[("Pilot / first-in-human", "Small n, feasibility & safety"), ("Pivotal study", "Statistically powered endpoints"),
               ("Regulatory submission", "Evidence package"), ("Post-approval study", "Conditions of approval"),
               ("PMCF / registries", "Lifetime evidence")], cols=5),
    "14.8": dict(t="hub", cap="Elements of a robust clinical study design",
        center="Study design",
        spokes=[("Clear endpoints", "Primary & secondary, clinically meaningful"), ("Comparator choice", "Control arm or performance goal"),
                ("Sample size", "Powered statistics"), ("Randomisation & blinding", "Bias control where feasible"),
                ("Inclusion / exclusion", "Defined population"), ("Statistical analysis plan", "Pre-specified methods")]),
    "14.9": dict(t="vflow", cap="Informed consent process",
        steps=[("Provide study information", "Purpose, procedures, risks, benefits, alternatives in lay language"),
               ("Allow time & answer questions", "No coercion; local language; impartial witness if needed"),
               ("? Subject freely agrees?", "Voluntary decision documented"),
               ("Sign & date consent form", "Copy given to participant; audio-visual where mandated (India)"),
               ("Re-consent on new information", "Protocol amendments, new risks")],
        edge_labels={2: "YES"}),
    "14.10": dict(t="hub", cap="GCP inspection focus areas",
        center="GCP compliance",
        spokes=[("Consent documentation", "Signed, dated, versioned"), ("Protocol adherence", "Deviations logged"),
                ("Data integrity", "Source-to-CRF traceability"), ("Safety reporting", "SAE timelines met"),
                ("Investigator oversight", "Delegation log, training"), ("Device accountability", "Shipment-use-return records")]),
    "14.11": dict(t="flow", cap="Clinical data flow from site to submission",
        steps=[("Source documents", "Hospital records"), ("Case report forms", "eCRF entry"),
               ("Monitoring & queries", "CRA source-data verification"), ("Database lock", "Clean, complete dataset"),
               ("Statistical analysis", "Per pre-specified SAP"), ("Clinical study report", "Feeds CER & submissions")], cols=3),
    "14.12": dict(t="vflow", cap="Adverse event management in a device trial",
        steps=[("Event observed / reported", "Any untoward medical occurrence"),
               ("Assess seriousness & causality", "Investigator assessment against definitions"),
               ("? Serious adverse event?", "Death, life-threatening, hospitalisation…"),
               ("Expedited reporting", "Sponsor → EC, CDSCO/FDA/CA within timelines"),
               ("Follow-up to resolution", "Outcome documented; trends reviewed by DSMB")],
        edge_labels={2: "YES"}),
    "14.13": dict(t="cycle", cap="PMCF integrated with the clinical evaluation lifecycle",
        steps=["CER conclusions", "PMCF plan", "Collect real-world data", "Registries & surveys",
               "PMCF evaluation report", "Update CER & risk file", "Inform SSCP / labelling"]),
    "14.14": dict(t="timeline", cap="Metal-on-metal hip implants — evidence timeline",
        events=[("1990s", "MoM bearings re-introduced"), ("2003–07", "Rapid adoption worldwide"),
                ("2008–10", "Registries flag high revision rates"), ("2010", "Major recall (ASR system)"),
                ("2011–13", "Regulatory alerts & follow-up imaging advice"), ("Legacy", "Stricter clinical evidence expectations")]),
}
